name: Bot CAESP Diario

on:
  schedule:
    - cron: '0 18 * * 1-5'  # segunda a sexta, 15h Brasília
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install selenium webdriver-manager requests

      - name: Run Bot
        run: python Monitor_de_Tarefas.py
